# -*- coding: utf-8 -*-
"""Scale_to_Win_PhoneBank_Reporting_Script(CA_Time).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vOrFUsQMOFyiZbgr7FFeTEhvQT8U9TCx

(This script is the result of asynchronous collaboration between Jonah Breslau and Torian Styles; original author: Jonah Breslau)

To run code within a cell, click into the cell, then press shift+enter. If it worked, you should see a green checkmark to the top-left of the cell.

This code imports relevant packages.
"""

import numpy as np
import pandas as pd
from datetime import *

from dateutil.parser import parse
from dateutil.tz import gettz

import pytz

"""Upload the file into the notebook (you can simply drag your file into the "files" sidebar; just make sure you are in the "content" subfolder).

Hover over your uploaded file, then click the three dots on the right of the highlighted file, then select "copy path".

Paste your file-path to the right of the equals-sign below, replacing what is already there, then wrap the file in quotation-marks.

"""

file = "/content/Faizah-16-QC-CEO-Signers-since-april-9-2026-05-10-22_38_12-dqixlkkm.csv"

"""This code corrects the dates by updating the timezone while also separating date from time. The newly created "Date" column will appear on the far-right of the updated .csv spreadsheet"""

pbframe = pd.read_csv(file)
pbframe["Date"] = pbframe["Call Date/Time"]
pbframe = pbframe.drop(['Call Date/Time'],axis=1)
#lambda function converts timezone from UTC to AZ time; .date method converts value to dat value only (i.e. drops time)
pbframe["Date"] = (pbframe["Date"].apply(lambda x : pd.Timestamp(x, tz='UTC').tz_convert('US/Pacific').date()))
print(pbframe["Date"].unique())


#assigns the index value of the "Canvass Result" column to the variable column_index
column_index = pbframe.columns.get_loc('Canvass Result')

print(column_index)
#assigns index value of last scaletowin question-column to variable last_col (lost column minus "Date")
last_col = (len(pbframe.columns)-1)
print(pbframe.columns[last_col])

"""This loops over the columns in the range we defined above, and appends the relevant column name as a prefix to each non-empty value in the column"""

from re import X
#for-loop to to assign prefix to values within column for crosstabulation
#pbframe.iloc[column_index-1:last_col+1] = pbframe.apply(lambda x: x.name+": " +x)
for i in range(column_index, last_col):
  col = pbframe.columns[i]
  pbframe[col] = pbframe[col].where(pbframe[col].isna(), f"{col}: " + pbframe[col].astype(str))
  #pbframe[pbframe.columns[i]] = str(pbframe.columns[i]) + ": " + pbframe[(pbframe.columns[i])].dropna()
  #pbframe[pbframe.columns[i]]= pbframe[pbframe.columns[i]].apply(lambda x: x.name+": " + x)
  #print(pbframe.columns[i])
pbframe.to_csv("fixeddates.csv")

"""Generate crosstabs for each date and combine (for-loop):"""

#summary = pd.crosstab(pbframe["Caller Name"],pbframe["Recall/Destitucion"])
#noncontact = pd.crosstab(pbframe["Caller Name"],pbframe["Canvass Result"])
#summary =summary.merge(noncontact, on="Caller Name")
#print(noncontact)


#empty list to store itereated dateframes
all_summaries = []

#first loop to iterate over unique dates
for i in pbframe["Date"].unique():
    print("Date:", i)
    dateframe = pbframe[pbframe["Date"] == i]

    #Base of loop--crosstabulates "Caller Name" with "Canvass Result"
    dt_summary = pd.crosstab(dateframe["Caller Name"], dateframe["Canvass Result"]).reset_index()
    #For-loops to merge crosstabulated questions
    for col in range(column_index, last_col-1):
        col_name = dateframe.columns[col+1]
        dt_summary_i = pd.crosstab(dateframe["Caller Name"], dateframe[col_name]).reset_index()

        #Outer-join ensures entries with no data/unpopulated columns are not lost when merging, minimizing information loss
        dt_summary = dt_summary.merge(dt_summary_i, on="Caller Name", how='outer')

    #Adds "Date" column to summary--value set to index
    dt_summary["Date"] = i
    #Appends dt_summary(i) to all_summaries
    all_summaries.append(dt_summary)

"""The following code concatenates all_summaries list into dataframe, then saves the final report to a .csv with today's date. It also alphabetizes the column names."""

today = date.today()

final_summary = pd.concat(all_summaries, ignore_index=True)

final_summary = final_summary.reindex(sorted(final_summary.columns), axis=1)
final_summary.to_csv(f"PB_Report_{today}.csv", index=False)